Создадим вектор размера 100, заполненный нулями:

In [12]:
import numpy as np
vector_zeros = np.zeros(100)
print(vector_zeros)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0.]


Создадим вектор размера 100, заполненный единицами:

In [13]:
vector_ones = np.ones(100)
print(vector_ones)

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]


Создадим вектор размера 100, заполненный тройками:

In [14]:
vector_threes = vector_ones * 3
print(vector_threes)

[3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.
 3. 3. 3. 3.]


Создадим матрицу:

In [15]:
matrix = np.eye(3)
print(matrix)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


В созданной матрице поменяем 1 и 2 строчку местами:

In [16]:
first_row = np.copy(matrix)[0]
matrix[0] = matrix[1]
matrix[1] = first_row
print(matrix)

[[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]]


Создадим вектор со значениями от 10 до 100:

In [18]:
vector_from_10_to_100 = np.arange(10, 101)
print(vector_from_10_to_100)

[ 10  11  12  13  14  15  16  17  18  19  20  21  22  23  24  25  26  27
  28  29  30  31  32  33  34  35  36  37  38  39  40  41  42  43  44  45
  46  47  48  49  50  51  52  53  54  55  56  57  58  59  60  61  62  63
  64  65  66  67  68  69  70  71  72  73  74  75  76  77  78  79  80  81
  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97  98  99
 100]


Создадим матрицу 4x4 и заполним её числами от 0 до 15:

In [19]:
matrix_from_0_to_15 = np.arange(0, 16)
matrix_from_0_to_15 = matrix_from_0_to_15.reshape(4, 4)
print(matrix_from_0_to_15)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


Создадим матрицу 3х3, заполненную единицами:

In [21]:
matrix_of_1 = np.ones(9)
matrix_of_1 = matrix_of_1.reshape(3, 3)
print(matrix_of_1)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Создадим трёхмерный массив, заполненный случайными значениями:

In [23]:
three_dimensional_array_with_random_values = np.random.default_rng(10).random((3, 3, 3)) # 10 - seed
print(three_dimensional_array_with_random_values)

[[[0.95600171 0.20768181 0.82844489]
  [0.14928212 0.51280462 0.1359196 ]
  [0.68903648 0.84174772 0.425509  ]]

 [[0.956926   0.82533291 0.33821531]
  [0.57576055 0.75330186 0.82710394]
  [0.93343847 0.14499469 0.74558021]]

 [[0.13935139 0.90652876 0.22611443]
  [0.85323975 0.30631787 0.96983037]
  [0.51783421 0.32247456 0.28243352]]]


Создадим матрицу 10х10, состоящую из случайных чисел:

In [24]:
matrix_with_random_values = np.random.default_rng(10).random((10, 10))
print(matrix_with_random_values)

[[0.95600171 0.20768181 0.82844489 0.14928212 0.51280462 0.1359196
  0.68903648 0.84174772 0.425509   0.956926  ]
 [0.82533291 0.33821531 0.57576055 0.75330186 0.82710394 0.93343847
  0.14499469 0.74558021 0.13935139 0.90652876]
 [0.22611443 0.85323975 0.30631787 0.96983037 0.51783421 0.32247456
  0.28243352 0.605865   0.33376446 0.67864877]
 [0.15442507 0.24977552 0.86989425 0.60036782 0.26198306 0.1494149
  0.13678915 0.24892094 0.38282467 0.64907906]
 [0.83756376 0.77603195 0.33951558 0.14856874 0.45701939 0.43786436
  0.57421759 0.37326922 0.63382506 0.11464436]
 [0.23309047 0.76724102 0.98712427 0.80800108 0.84296564 0.79568268
  0.45684131 0.73867068 0.57845499 0.45073557]
 [0.27102442 0.86460315 0.06865567 0.81673446 0.881835   0.42351639
  0.83322931 0.34101671 0.51979151 0.54920645]
 [0.19287718 0.33321689 0.27752456 0.45755893 0.67484562 0.68383122
  0.52361312 0.46437257 0.50862936 0.32460429]
 [0.1726007  0.29933345 0.64856728 0.06471591 0.63370843 0.27900152
  0.18595992 0

Найдём минимум и максимум:

In [26]:
min_of_matrix = np.min(matrix_with_random_values)
max_of_matrix = np.max(matrix_with_random_values)
print("min = ", min_of_matrix, ", max = ", max_of_matrix)

min =  0.01303743209502628 , max =  0.9871242718900939


Создадим вектор размера 30 со случайными числами и найдём их среднее арифметическое:

In [27]:
vector_of_30_random_values = np.random.default_rng(10).random(30)
mean_of_vector = np.mean(vector_of_30_random_values)
print(mean_of_vector)

0.5663161660577832


Создадим трёхмерный массив размерности (6, 7, 8), заполненный случайными числами. Найдём позицию (x, y, z) сотого элемента:

In [41]:
three_dimensional_array = np.random.default_rng(10).random((6, 7, 8))
value = three_dimensional_array.flat[100]
position = np.where(three_dimensional_array == value)
print(position[0][0], " ", position[1][0], " ", position[2][0])

1   5   4


Создадим две матрицы: 5x3 и 3x2. Перемножим их:

In [42]:
matrix_5_x_3 = np.eye(5, 3)
matrix_3_x_2 = np.eye(3, 2)
product = np.matmul(matrix_5_x_3, matrix_3_x_2)
print(product)

[[1. 0.]
 [0. 1.]
 [0. 0.]
 [0. 0.]
 [0. 0.]]


Создадим вектор размерности 100 со значениями от 0 до 10. Если значение находится между 3 и 8, то поменяем знак у элемента

In [44]:
vector_from_0_to_10 = np.random.default_rng(10).random(100) * 10
print(vector_from_0_to_10)
with np.nditer(vector_from_0_to_10, op_flags=['readwrite']) as it:
    for x in it:
        if 3 <= x <= 8:
            x[...] = (-1) * x
print(vector_from_0_to_10)

[9.5600171  2.0768181  8.28444885 1.49282123 5.12804616 1.35919604
 6.8903648  8.41747724 4.25508997 9.56926003 8.25332906 3.38215312
 5.75760548 7.53301865 8.27103937 9.33438471 1.44994695 7.45580211
 1.39351394 9.06528756 2.26114434 8.5323975  3.06317866 9.69830368
 5.17834214 3.22474559 2.82433517 6.05864996 3.33764457 6.78648774
 1.5442507  2.49775519 8.69894246 6.0036782  2.61983056 1.49414901
 1.36789149 2.48920938 3.82824667 6.49079057 8.3756376  7.76031947
 3.39515575 1.48568738 4.57019387 4.37864358 5.7421759  3.73269224
 6.33825057 1.14644359 2.33090474 7.67241017 9.87124272 8.08001079
 8.42965644 7.95682679 4.56841307 7.38670675 5.78454993 4.50735567
 2.71024418 8.64603147 0.68655666 8.1673446  8.81834999 4.23516393
 8.33229314 3.41016713 5.19791507 5.49206449 1.92877183 3.33216886
 2.77524559 4.57558932 6.74845622 6.83831219 5.23613118 4.6437257
 5.0862936  3.24604286 1.72600705 2.9933345  6.48567279 0.64715908
 6.33708434 2.79001519 1.85959924 4.89048125 3.53685082 0.96202

Создадим матрицу 5x5 со значениями от 0 до 4

In [45]:
matrix_5_x_5 = np.zeros((5, 5))
counter = 0
for row in matrix_5_x_5:
    row += counter
    counter += 1
print(matrix_5_x_5)

[[0. 0. 0. 0. 0.]
 [1. 1. 1. 1. 1.]
 [2. 2. 2. 2. 2.]
 [3. 3. 3. 3. 3.]
 [4. 4. 4. 4. 4.]]


Создадим матрицу 10x10 со случайными значениями, вычислим среднее и вычтем из каждой строки:

In [46]:
matrix_10_x_10 = np.random.default_rng(10).random((10, 10))
print(matrix_10_x_10)
mean = np.mean(matrix_10_x_10)
print(mean)
for row in matrix_10_x_10:
    row -= mean
print(matrix_10_x_10)

[[0.95600171 0.20768181 0.82844489 0.14928212 0.51280462 0.1359196
  0.68903648 0.84174772 0.425509   0.956926  ]
 [0.82533291 0.33821531 0.57576055 0.75330186 0.82710394 0.93343847
  0.14499469 0.74558021 0.13935139 0.90652876]
 [0.22611443 0.85323975 0.30631787 0.96983037 0.51783421 0.32247456
  0.28243352 0.605865   0.33376446 0.67864877]
 [0.15442507 0.24977552 0.86989425 0.60036782 0.26198306 0.1494149
  0.13678915 0.24892094 0.38282467 0.64907906]
 [0.83756376 0.77603195 0.33951558 0.14856874 0.45701939 0.43786436
  0.57421759 0.37326922 0.63382506 0.11464436]
 [0.23309047 0.76724102 0.98712427 0.80800108 0.84296564 0.79568268
  0.45684131 0.73867068 0.57845499 0.45073557]
 [0.27102442 0.86460315 0.06865567 0.81673446 0.881835   0.42351639
  0.83322931 0.34101671 0.51979151 0.54920645]
 [0.19287718 0.33321689 0.27752456 0.45755893 0.67484562 0.68383122
  0.52361312 0.46437257 0.50862936 0.32460429]
 [0.1726007  0.29933345 0.64856728 0.06471591 0.63370843 0.27900152
  0.18595992 0